services:
  dev-database:
    image: postgres:15.0
    container_name: dev-database
    ports:
      - 5434:5432 #{port in host (PC)} : {port in container}
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Abc123456
      POSTGRES_DB: testdb
    networks:
      - netjs-network
networks:
  netjs-network:
    driver: bridge