version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: nestjs-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: nestjs_auth_crud
      MYSQL_USER: nestuser
      MYSQL_PASSWORD: nestpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: